version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: media_user
      POSTGRES_PASSWORD: secretpw
      POSTGRES_DB: media_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U media_user -d media_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://media_user:secretpw@db:5432/media_db
      AUTH_TOKEN: your-secret-token
    volumes:
      - data_media:/data

volumes:
  db_data:
  data_media: {}
