version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      # 외부와 내부 모두 접근 가능하도록 리스너 설정
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  bridge:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - GENERATOR_ENDPOINT=http://generator:9001/generate
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC=video-callback
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-flash}
    depends_on:
      - kafka
      - generator

  generator:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn generator_server:app --host 0.0.0.0 --port 9001
    ports:
      - "9001:9001"
    environment:
      - COMFY_BASE_URL=http://host.docker.internal:8188
      - WORKFLOW_JSON_PATH=/app/videotest3.json
      - BRIDGE_CALLBACK_URL=http://bridge:8000/api/video/callback
