version: "3.9"

services:
  generator:
    build:
      context: ./prompt
      dockerfile: Dockerfile
    command: uvicorn generator_server:app --host 0.0.0.0 --port 9001
    ports:
      - "19001:19001"
    environment:
      - COMFY_BASE_URL=http://host.docker.internal:8188
      - WORKFLOW_JSON_PATH=/app/videotest3.json
      - BRIDGE_CALLBACK_URL=http://bridge:8000/api/video/callback
