version: "3.9"

services:
  generator_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generator_server
    restart: always
    environment:
      - COMFY_BASE_URL=http://host.docker.internal:8188
      - WORKFLOW_YT_PATH=/app/youtube_video.json
      - WORKFLOW_REDDIT_PATH=/app/reddit_image.json
      - BRIDGE_CALLBACK_URL=http://host.docker.internal:8001/api/media/callback
      - POLL_INTERVAL=2.0
      - OUTPUT_DIR=/app/output   # 컨테이너 안에서 output 폴더 경로
    volumes:
      - ./youtube_video.json:/app/youtube_video.json
      - ./reddit_image.json:/app/reddit_image.json
      - D:/ComfyUI/ComfyUI/output:/app/output   # 로컬 output 폴더 공유
    ports:
      - "19001:9001"
