version : "3.8"
services:
  prompt:
    build: 
      context: ./prompt
    image: prompt_app:local
    command: uvicorn prompt_service:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"